name: Start parser
on:
  schedule:
    - cron: 30 8 * * * # Every day at 8:30 UTC (10:30 KIEV)
  workflow_dispatch:

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Cook the .env
        run: cp .env.example .env && echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> ./.env
      - name: Start parser
        run: npm run start
