name: Parse casualties
on:
  schedule:
    - cron: 0 23 * * * # Every day at 11:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.13.0'
      - run: cp .env.example .env && echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> ./.env
      - run: npm i && npm run start
